version: "2"
networks:
  mybutt:
    external:
      name: mybutt_default
  sshclient:
    external:
      name: sshclient_default
services:
  nginx:
    build: .
    image: MYBUTT/nginx
    external_links:
      - mybutt_mybutt_1:mybutt
    networks:
      - mybutt
      - sshclient
    ports:
      - "80:80"
    restart: always
